// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByiz4b2cE8eO4brKEuKk4_XhlWaTRjOFg',
    appId: '1:191977747644:web:9623fb264d42e11a04ccb9',
    messagingSenderId: '191977747644',
    projectId: 'acheeclass',
    authDomain: 'acheeclass.firebaseapp.com',
    storageBucket: 'acheeclass.appspot.com',
    measurementId: 'G-FMQ3BTLRN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhdNnAbQw7bCbS8C9FFOnsTBz3aGXGY_k',
    appId: '1:191977747644:android:70b839108eb01b1f04ccb9',
    messagingSenderId: '191977747644',
    projectId: 'acheeclass',
    storageBucket: 'acheeclass.appspot.com',
  );
}
